### ISSUE TITLE
Each user should only be able to upload one review per resource

### ISSUE THREAD

**Issue by jsms90** [FAC9/the-badgerer#125]

**Comment by Jwhiles** [comment]
I agree

**Comment by Jwhiles** [comment]
actually

**Comment by Jwhiles** [comment]
what if a user wants to track the evolution of their critical opinions? Re-reviewing is a time honoured tradition in movies etc, and we don't pretend the first review never happened.

**Comment by Jwhiles** [comment]
coding resources are like movies, is what I'm saying.

**Comment by denesnori** [comment]
:D I think we should allow multiple reviews from  a user. We can discuss this issue later if we have time :)
