### ISSUE TITLE
dbRequests where you 'INSERT INTO' and hence redirect. Where query returning 'data'

### ISSUE THREAD

**Issue by SavageWilliam** [FAC9/the-badgerer#128]
Using addreview.js again as an example:

In the callback of the database request you return 'data'. However (because you're inserting data and not returning anything from the database) this isn't used in addReviewHandler.js

You could.... 

1) return nothing and just handle the error?

2 use "RETURNING resource_id" at the end of your sql statement. Example: (when creating a user)

INSERT INTO users(firstname, lastname, github, email, username, password) VALUES
                  ($1, $2, $3, $4, $5, $6) RETURNING id, username`

This 'resource_id' could then be used in the reply.redirection (addReviewHander.js line:20). Just to ensure that this value is coming from the database rather than the original request payload.. 
Might not be a problem in your example, but potentially a useful tool for something else

**Comment by emilyb7** [comment]
cheers @SavageWilliam , i only just discovered the "returning" method in sql when looking at your group's code. I will try and get this to work :)
