### ISSUE TITLE
File naming

### ISSUE THREAD

**Issue by SavageWilliam** [FAC9/the-badgerer#129]
[Avoid capitals in file names](http://stackoverflow.com/questions/1594014/how-do-i-explain-my-colleagues-that-filenames-should-not-contain-uppercase-chara) - theres a mixture of naming conventions in the files. 

I'm sure you're aware of this and it's due to different pairs working on different modules. 

I like the '-' and '_'. you've used, for example: 

resource_query.js
user-query.js 

Choosing one will make all your files much easier to traverse :D

**Comment by otajor** [comment]
Yeah this is impressively inconsistent 😄 looks like 4 different naming conventions?
<img width="170" alt="screen shot 2016-12-02 at 11 33 39" src="https://cloud.githubusercontent.com/assets/13705650/20832639/427d4ea0-b883-11e6-997e-8bd303e70da8.png">

**Comment by otajor** [comment]
P.S. jury is currently out on whether you can/should use capital letters in file names. We've always used camel case in the past, but as @SavageWilliam 's issue points out there are good reasons for only using lowercase...

**Comment by sohilpandya** [comment]
@SavageWilliam I don't think that is the right way of doing it in my opinion. 

I would rather they stick to camel casing the file names and keeping to that structure. (but again that is my opinion) 

As @Jbarget pointed out to us that the issue you've linked to is 7 years old and not that popular. 

![](https://files.gitter.im/foundersandcoders/FAC9-Planning/ijSv/Screen-Shot-2016-12-02-at-12.04.37.png)

**Comment by emilyb7** [comment]
we have gone for camerl case... but it turns out that renaming files breaks heroku, so no more of that for now
