### ISSUE TITLE
Why cb first argument in your db functions

### ISSUE THREAD

**Issue by jay-meister** [FAC9/the-badgerer#133]
Code, readme  and project looks great 😄 

I was wondering why you chose to pass the cb as first argument in your db functions?

**Comment by emilyb7** [comment]
@JMurphyWeb thanks! :D Not sure that passing the cb as the first argument was any kind of conscious decision on our part. What should we have done?

**Comment by Jwhiles** [comment]
I agree it was something we didn't think about. And doing so definitely caused some quite confusing function calls, especially when we nested our callbacks.

**Comment by jay-meister** [comment]
hehe yeah it is generally the last argument that you pass. 

Project really does look great!
