### ISSUE TITLE
fix indentation in views

### ISSUE THREAD

**Issue by jsms90** [FAC9/the-badgerer#139]
- [label & textarea](https://github.com/FAC9/the-badgerer/blob/master/views/add_new_user.html) tags at same level
- [textarea, label & select](https://github.com/FAC9/the-badgerer/blob/master/views/edit.html) should be at same level
- [h3 & divs](https://github.com/FAC9/the-badgerer/blob/master/views/home.html)
- [this](https://github.com/FAC9/the-badgerer/blob/master/views/resource_profile.html) & [this](https://github.com/FAC9/the-badgerer/blob/master/views/user_profile.html) would more readable with div contents on a new line:
```
  <div class='reviews-container'>
    {{> reviews fromResourceProfile=true}}
  </div>
```
- [a tag](https://github.com/FAC9/the-badgerer/blob/master/views/partials/login_header.html)
- be consistent with whether you indent after {{if}} and {{each}} statements

**Comment by denesnori** [comment]
Done :)
